image: node:7

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
  expire_in: 1 week

unit tests:
  stage: test
  script:
    - npm run unit-tests

deploy to dev:
  stage: deploy
  script:
    - npm run deploy -- --dev
  except:
    - master
  environment:
    name: dev

deploy to production:
  stage: deploy
  script:
    - npm run deploy -- --prod
  only:
    - master
  environment:
    name: prod
