image: node:7

stages:
  - prepare
  - build
  - test
  - deploy

install node modules:
  stage: prepare
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

download graphql schema:
  state: prepare
  script:
    - npm run fetch-schema
  artifacts:
    paths:
      - schema.json

build:
  stage: build
  script:
    - npm run build

unit tests:
  stage: test
  script:
    - npm run unit-tests

deploy to dev:
  stage: deploy
  script:
    - npm run deploy
  except:
    - master
  environment:
    name: dev

deploy to production:
  stage: deploy
  script:
    - npm run deploy
  only:
    - master
  environment:
    name: prod
