version: '3'
services:
  ui:
    image: node:8.1.1-alpine
    tty: true
    volumes:
      - ./packages/ui/:/usr/app
    working_dir: /usr/app/
    command: yarn server:dev
    environment:
      - NODE_ENV=development
      - HOST=dockerhost
      - PORT=3000
    ports:
      - 3000:3000
    links:
      - gateway

  gateway:
    image: node:8.1.1-alpine
    tty: true
    volumes:
      - ./packages/gateway/:/usr/app
    working_dir: /usr/app/
    command: yarn server:dev
    environment:
      - NODE_ENV=development
      - HOST=dockerhost
      - PORT=4000
      - POSTGRES_HOST=store
      - POSTGRES_PORT=5432
      - POSTGRES_DB=saas_starter
      - POSTGRES_USER=slightlytyler
      - POSTGRES_PASSWORD=a1b2c3d4e5
    ports:
      - 4000:80
    depends_on:
      - store
    links:
      - store

  store:
    build: ./packages/store
    environment:
      POSTGRES_DB: saas_starter
      POSTGRES_USER: slightlytyler
      POSTGRES_PASSWORD: a1b2c3d4e5
    ports:
      - 6000:5432
