// flow-typed signature: 351909d3eb6af77b6734ef2bf85ad4bd
// flow-typed version: <<STUB>>/auth0-lock-passwordless_v^2.2.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-lock-passwordless'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-lock-passwordless' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-lock-passwordless/lib/atom/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/browser' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/country_codes' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/email/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/email/ask_email' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/email/email_input' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/email/email_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/input_wrap' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_email' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_phone_number' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/ask_location' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/ask_phone_number' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/location_input' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/location_select' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/phone_number_input' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/phone-number/phone_number_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/social/ask_social_network' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/social/social_button' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/social/social_buttons_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/storage' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/vcode/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/vcode/ask_vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/vcode/vcode_input' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/cred/vcode/vcode_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/dict/dicts' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/dict/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/dict/t' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/gravatar/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/gravatar/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/gravatar/web_api' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/header/background' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/header/header' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/header/icon' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/header/welcome_message' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/header/welcome' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/icon/button' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/icon/icon' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/icon/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/avatar' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/badge' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/chrome' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/confirmation_pane' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/container_manager' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/global_error' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/lock' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/pane_separator' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/plugin_manager' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/render_scheduler' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/renderer' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/screen' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/signed_in_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/submit_button' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/terms' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/lock/web_api' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/emailcode/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/magiclink/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/sms/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/social-or-emailcode/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/social-or-magiclink/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/social-or-sms/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/mode/social/spec' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/multisize-slide/multisize_slide' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/ask_email_vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/ask_email' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/ask_phone_number_vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/ask_phone_number' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/ask_vcode' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/email_sent_confirmation' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/passwordless/magiclink' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/preload/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/social/actions' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/social/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/store/index' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/esc_keydown_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/fn_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/id_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/jsonp_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/media_utils' {
  declare module.exports: any;
}

declare module 'auth0-lock-passwordless/lib/utils/string_utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-lock-passwordless/lib/atom/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/atom/index'>;
}
declare module 'auth0-lock-passwordless/lib/browser.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/browser'>;
}
declare module 'auth0-lock-passwordless/lib/cred/country_codes.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/country_codes'>;
}
declare module 'auth0-lock-passwordless/lib/cred/email/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/email/actions'>;
}
declare module 'auth0-lock-passwordless/lib/cred/email/ask_email.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/email/ask_email'>;
}
declare module 'auth0-lock-passwordless/lib/cred/email/email_input.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/email/email_input'>;
}
declare module 'auth0-lock-passwordless/lib/cred/email/email_pane.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/email/email_pane'>;
}
declare module 'auth0-lock-passwordless/lib/cred/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/index'>;
}
declare module 'auth0-lock-passwordless/lib/cred/input_wrap.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/input_wrap'>;
}
declare module 'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_email.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_email'>;
}
declare module 'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_phone_number.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/or/ask_social_network_or_phone_number'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/actions'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/ask_location.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/ask_location'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/ask_phone_number.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/ask_phone_number'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/index'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/location_input.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/location_input'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/location_select.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/location_select'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/phone_number_input.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/phone_number_input'>;
}
declare module 'auth0-lock-passwordless/lib/cred/phone-number/phone_number_pane.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/phone-number/phone_number_pane'>;
}
declare module 'auth0-lock-passwordless/lib/cred/social/ask_social_network.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/social/ask_social_network'>;
}
declare module 'auth0-lock-passwordless/lib/cred/social/social_button.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/social/social_button'>;
}
declare module 'auth0-lock-passwordless/lib/cred/social/social_buttons_pane.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/social/social_buttons_pane'>;
}
declare module 'auth0-lock-passwordless/lib/cred/storage.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/storage'>;
}
declare module 'auth0-lock-passwordless/lib/cred/vcode/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/vcode/actions'>;
}
declare module 'auth0-lock-passwordless/lib/cred/vcode/ask_vcode.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/vcode/ask_vcode'>;
}
declare module 'auth0-lock-passwordless/lib/cred/vcode/vcode_input.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/vcode/vcode_input'>;
}
declare module 'auth0-lock-passwordless/lib/cred/vcode/vcode_pane.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/cred/vcode/vcode_pane'>;
}
declare module 'auth0-lock-passwordless/lib/dict/dicts.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/dict/dicts'>;
}
declare module 'auth0-lock-passwordless/lib/dict/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/dict/index'>;
}
declare module 'auth0-lock-passwordless/lib/dict/t.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/dict/t'>;
}
declare module 'auth0-lock-passwordless/lib/gravatar/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/gravatar/actions'>;
}
declare module 'auth0-lock-passwordless/lib/gravatar/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/gravatar/index'>;
}
declare module 'auth0-lock-passwordless/lib/gravatar/web_api.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/gravatar/web_api'>;
}
declare module 'auth0-lock-passwordless/lib/header/background.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/header/background'>;
}
declare module 'auth0-lock-passwordless/lib/header/header.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/header/header'>;
}
declare module 'auth0-lock-passwordless/lib/header/icon.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/header/icon'>;
}
declare module 'auth0-lock-passwordless/lib/header/welcome_message.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/header/welcome_message'>;
}
declare module 'auth0-lock-passwordless/lib/header/welcome.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/header/welcome'>;
}
declare module 'auth0-lock-passwordless/lib/icon/button.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/icon/button'>;
}
declare module 'auth0-lock-passwordless/lib/icon/icon.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/icon/icon'>;
}
declare module 'auth0-lock-passwordless/lib/icon/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/icon/index'>;
}
declare module 'auth0-lock-passwordless/lib/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/index'>;
}
declare module 'auth0-lock-passwordless/lib/lock/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/actions'>;
}
declare module 'auth0-lock-passwordless/lib/lock/avatar.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/avatar'>;
}
declare module 'auth0-lock-passwordless/lib/lock/badge.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/badge'>;
}
declare module 'auth0-lock-passwordless/lib/lock/chrome.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/chrome'>;
}
declare module 'auth0-lock-passwordless/lib/lock/confirmation_pane.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/confirmation_pane'>;
}
declare module 'auth0-lock-passwordless/lib/lock/container_manager.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/container_manager'>;
}
declare module 'auth0-lock-passwordless/lib/lock/global_error.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/global_error'>;
}
declare module 'auth0-lock-passwordless/lib/lock/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/index'>;
}
declare module 'auth0-lock-passwordless/lib/lock/lock.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/lock'>;
}
declare module 'auth0-lock-passwordless/lib/lock/pane_separator.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/pane_separator'>;
}
declare module 'auth0-lock-passwordless/lib/lock/plugin_manager.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/plugin_manager'>;
}
declare module 'auth0-lock-passwordless/lib/lock/render_scheduler.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/render_scheduler'>;
}
declare module 'auth0-lock-passwordless/lib/lock/renderer.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/renderer'>;
}
declare module 'auth0-lock-passwordless/lib/lock/screen.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/screen'>;
}
declare module 'auth0-lock-passwordless/lib/lock/signed_in_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/signed_in_confirmation'>;
}
declare module 'auth0-lock-passwordless/lib/lock/submit_button.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/submit_button'>;
}
declare module 'auth0-lock-passwordless/lib/lock/terms.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/terms'>;
}
declare module 'auth0-lock-passwordless/lib/lock/web_api.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/lock/web_api'>;
}
declare module 'auth0-lock-passwordless/lib/mode/emailcode/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/emailcode/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/index'>;
}
declare module 'auth0-lock-passwordless/lib/mode/magiclink/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/magiclink/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/sms/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/sms/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/social-or-emailcode/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/social-or-emailcode/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/social-or-magiclink/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/social-or-magiclink/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/social-or-sms/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/social-or-sms/spec'>;
}
declare module 'auth0-lock-passwordless/lib/mode/social/spec.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/mode/social/spec'>;
}
declare module 'auth0-lock-passwordless/lib/multisize-slide/multisize_slide.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/multisize-slide/multisize_slide'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/actions'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/ask_email_vcode.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/ask_email_vcode'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/ask_email.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/ask_email'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/ask_phone_number_vcode.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/ask_phone_number_vcode'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/ask_phone_number.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/ask_phone_number'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/ask_vcode.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/ask_vcode'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/email_sent_confirmation.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/email_sent_confirmation'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/index'>;
}
declare module 'auth0-lock-passwordless/lib/passwordless/magiclink.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/passwordless/magiclink'>;
}
declare module 'auth0-lock-passwordless/lib/preload/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/preload/index'>;
}
declare module 'auth0-lock-passwordless/lib/social/actions.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/social/actions'>;
}
declare module 'auth0-lock-passwordless/lib/social/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/social/index'>;
}
declare module 'auth0-lock-passwordless/lib/store/index.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/store/index'>;
}
declare module 'auth0-lock-passwordless/lib/utils/esc_keydown_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/esc_keydown_utils'>;
}
declare module 'auth0-lock-passwordless/lib/utils/fn_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/fn_utils'>;
}
declare module 'auth0-lock-passwordless/lib/utils/id_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/id_utils'>;
}
declare module 'auth0-lock-passwordless/lib/utils/jsonp_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/jsonp_utils'>;
}
declare module 'auth0-lock-passwordless/lib/utils/media_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/media_utils'>;
}
declare module 'auth0-lock-passwordless/lib/utils/string_utils.js' {
  declare module.exports: $Exports<'auth0-lock-passwordless/lib/utils/string_utils'>;
}
