// flow-typed signature: 1472b1fd5725673b91daec87a9e8ac1c
// flow-typed version: <<STUB>>/eslint-plugin-lodash-fp_v^2.1.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-lodash-fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-lodash-fp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-lodash-fp/rules/consistent-compose' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/consistent-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/core/ast-util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/core/constants' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/core/enhance' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/core/lodash-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/core/lodash-util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-argumentless-calls' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-chain' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-function-wrapping' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-iteratee-args' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-for-each' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-partial-of-curried' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-single-composition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-submodule-destructuring' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/no-unused-result' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-compact' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-composition-grouping' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-constant' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-flat-map' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-get' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/prefer-identity' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/preferred-alias' {
  declare module.exports: any;
}

declare module 'eslint-plugin-lodash-fp/rules/use-fp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-lodash-fp/index' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp'>;
}
declare module 'eslint-plugin-lodash-fp/index.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp'>;
}
declare module 'eslint-plugin-lodash-fp/rules/consistent-compose.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/consistent-compose'>;
}
declare module 'eslint-plugin-lodash-fp/rules/consistent-name.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/consistent-name'>;
}
declare module 'eslint-plugin-lodash-fp/rules/core/ast-util.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/core/ast-util'>;
}
declare module 'eslint-plugin-lodash-fp/rules/core/constants.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/core/constants'>;
}
declare module 'eslint-plugin-lodash-fp/rules/core/enhance.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/core/enhance'>;
}
declare module 'eslint-plugin-lodash-fp/rules/core/lodash-data.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/core/lodash-data'>;
}
declare module 'eslint-plugin-lodash-fp/rules/core/lodash-util.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/core/lodash-util'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-argumentless-calls.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-argumentless-calls'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-chain.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-chain'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-args.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-extraneous-args'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-function-wrapping.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-extraneous-function-wrapping'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-extraneous-iteratee-args.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-extraneous-iteratee-args'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-for-each.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-for-each'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-partial-of-curried.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-partial-of-curried'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-single-composition.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-single-composition'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-submodule-destructuring.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-submodule-destructuring'>;
}
declare module 'eslint-plugin-lodash-fp/rules/no-unused-result.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/no-unused-result'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-compact.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-compact'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-composition-grouping.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-composition-grouping'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-constant.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-constant'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-flat-map.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-flat-map'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-get.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-get'>;
}
declare module 'eslint-plugin-lodash-fp/rules/prefer-identity.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/prefer-identity'>;
}
declare module 'eslint-plugin-lodash-fp/rules/preferred-alias.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/preferred-alias'>;
}
declare module 'eslint-plugin-lodash-fp/rules/use-fp.js' {
  declare module.exports: $Exports<'eslint-plugin-lodash-fp/rules/use-fp'>;
}
