// flow-typed signature: ac5198499f53d59d6cd307f4be40913d
// flow-typed version: <<STUB>>/react-layout-components_v^3.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-layout-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-layout-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-layout-components/lib/components/Anchor' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/Box' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/Container' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/Page' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/ScrollView' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/shortcut/Center' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/shortcut/Flex' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/shortcut/VBox' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/components/TabView' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/index' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Anchor' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Border' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Card' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Horizontal' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Tab' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/layouts/Vertical' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/utils/omit' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/utils/props' {
  declare module.exports: any;
}

declare module 'react-layout-components/lib/utils/warn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-layout-components/lib/components/Anchor.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/Anchor'>;
}
declare module 'react-layout-components/lib/components/Box.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/Box'>;
}
declare module 'react-layout-components/lib/components/Container.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/Container'>;
}
declare module 'react-layout-components/lib/components/Page.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/Page'>;
}
declare module 'react-layout-components/lib/components/ScrollView.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/ScrollView'>;
}
declare module 'react-layout-components/lib/components/shortcut/Center.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/shortcut/Center'>;
}
declare module 'react-layout-components/lib/components/shortcut/Flex.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/shortcut/Flex'>;
}
declare module 'react-layout-components/lib/components/shortcut/VBox.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/shortcut/VBox'>;
}
declare module 'react-layout-components/lib/components/TabView.js' {
  declare module.exports: $Exports<'react-layout-components/lib/components/TabView'>;
}
declare module 'react-layout-components/lib/index.js' {
  declare module.exports: $Exports<'react-layout-components/lib/index'>;
}
declare module 'react-layout-components/lib/layouts/Anchor.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Anchor'>;
}
declare module 'react-layout-components/lib/layouts/Border.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Border'>;
}
declare module 'react-layout-components/lib/layouts/Card.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Card'>;
}
declare module 'react-layout-components/lib/layouts/Horizontal.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Horizontal'>;
}
declare module 'react-layout-components/lib/layouts/Tab.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Tab'>;
}
declare module 'react-layout-components/lib/layouts/Vertical.js' {
  declare module.exports: $Exports<'react-layout-components/lib/layouts/Vertical'>;
}
declare module 'react-layout-components/lib/utils/omit.js' {
  declare module.exports: $Exports<'react-layout-components/lib/utils/omit'>;
}
declare module 'react-layout-components/lib/utils/props.js' {
  declare module.exports: $Exports<'react-layout-components/lib/utils/props'>;
}
declare module 'react-layout-components/lib/utils/warn.js' {
  declare module.exports: $Exports<'react-layout-components/lib/utils/warn'>;
}
