// flow-typed signature: 7c22cfb9eba769ef1029532d4b730fd5
// flow-typed version: <<STUB>>/react-async-component_v^0.2.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-component/commonjs/AsyncComponentProvider' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/constants' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/createAsyncComponent' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/IdProvider' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/ssr/ClientProvider' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/ssr/constants' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/ssr/resolveAsyncComponents' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/ssr/ServerProvider' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/ssr/withAsyncComponents' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/types' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/withAsyncComponents' {
  declare module.exports: any;
}

declare module 'react-async-component/umd/npm-library-starter' {
  declare module.exports: any;
}

declare module 'react-async-component/umd/react-async-component' {
  declare module.exports: any;
}

declare module 'react-async-component/umd/react-async-component.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-component/commonjs/AsyncComponentProvider.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/AsyncComponentProvider'>;
}
declare module 'react-async-component/commonjs/constants.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/constants'>;
}
declare module 'react-async-component/commonjs/createAsyncComponent.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/createAsyncComponent'>;
}
declare module 'react-async-component/commonjs/IdProvider.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/IdProvider'>;
}
declare module 'react-async-component/commonjs/index.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/index'>;
}
declare module 'react-async-component/commonjs/ssr/ClientProvider.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/ssr/ClientProvider'>;
}
declare module 'react-async-component/commonjs/ssr/constants.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/ssr/constants'>;
}
declare module 'react-async-component/commonjs/ssr/resolveAsyncComponents.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/ssr/resolveAsyncComponents'>;
}
declare module 'react-async-component/commonjs/ssr/ServerProvider.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/ssr/ServerProvider'>;
}
declare module 'react-async-component/commonjs/ssr/withAsyncComponents.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/ssr/withAsyncComponents'>;
}
declare module 'react-async-component/commonjs/types.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/types'>;
}
declare module 'react-async-component/commonjs/withAsyncComponents.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/withAsyncComponents'>;
}
declare module 'react-async-component/umd/npm-library-starter.js' {
  declare module.exports: $Exports<'react-async-component/umd/npm-library-starter'>;
}
declare module 'react-async-component/umd/react-async-component.js' {
  declare module.exports: $Exports<'react-async-component/umd/react-async-component'>;
}
declare module 'react-async-component/umd/react-async-component.min.js' {
  declare module.exports: $Exports<'react-async-component/umd/react-async-component.min'>;
}
